apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../kustomize/prometheus
- ../../kustomize/grafana
- ../../kustomize/topologies/pod2pod/overlays/service
patchesStrategicMerge:
- |-
  $patch: delete
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: pod2pod-client
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: pod2pod-server
  spec:
    template:
      spec:
        containers:
          - name: main
            command: ["netserver", "-D", "-4"]
            ports:
            - containerPort: 12865
              name: netperf
              protocol: TCP
            - containerPort: 12866
              name: netperf-data
              protocol: TCP
- |-
  apiVersion: v1
  kind: Service
  metadata:
    name: pod2pod-server
  spec:
    type: LoadBalancer
    ports:
      - protocol: TCP
        port: 12865
        targetPort: 12865
        name: netperf
      - protocol: TCP
        port: 12866
        targetPort: 12866
        name: netperf-data
images:
- name: k8s.gcr.io/pause:3.1
  newName: nixery.dev/bash/coreutils/iproute2/iputils/bind/procps/netperf
