kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: egw-scale-test
networking:
  disableDefaultCNI: true
  kubeProxyMode: "none"
nodes:
- role: worker
  labels:
    role.scaffolding/egw-client: "true"
- role: worker
  labels:
    role.scaffolding/egw-node: "true"
- role: worker
  labels:
    role.scaffolding/monitoring: "true"
- role: worker
  labels:
    cilium.io/no-schedule: "true"
- role: control-plane

