---
- name: Pull specific cilium-cli version
  shell: |
      curl -sSL --remote-name-all https://github.com/cilium/cilium-cli/releases/download/{{ cilium['cli_version'] }}/cilium-linux-amd64.tar.gz
      tar xzvfC cilium-linux-amd64.tar.gz /tmp
      rm cilium-linux-amd64.tar.gz
      export KUBECONFIG={{kubeconfig}};/tmp/cilium version

- name: Install using Cilium cli
  shell: |
      export KUBECONFIG={{kubeconfig}};/tmp/cilium install {{cilium['install_params']}}