apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry
commonLabels:
  app.kubernetes.io/name: registry
  app.kubernetes.io/part-of: scaffolding
resources:
- namespace.yaml
- deployment.yaml
- service.yaml