version: 2.1
setup: true
parameters:
  run_pipeline:
    type: boolean
    default: false
  skip_image_build_pipeline:
    type: boolean
    default: false
orbs:
  docker: circleci/docker@2.1.1
  python: circleci/python@2.0.3
  continuation: circleci/continuation@0.1.0
executor:
  base:
    docker:
      - image: cimg/base
        tag: stable
jobs:
  generate_config:
    executor:
      name: python/default
      tag: '3.10'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ci/
      - run:
          name: Generate Pipeline Assets
          command: |
            mkdir -p /tmp/generated
            python3 ci/circleci.py /tmp/generated --build-image
      - persist_to_workspace:
          root: /tmp/generated/
          paths:
            - pipeline.yml
            - build.yml
      - store_artifacts:
          path: /tmp/generated
  run_config:
    executor: continuation/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Show image build triggers
          command: |
            echo Condition variables for building images:
            echo pipeline.git.tag \"<< pipeline.git.tag >>\"
            echo pipeline.git.branch \"<< pipeline.git.branch >>\"
            echo pipeline.parameters.skip_image_build_pipeline \"<< pipeline.parameters.skip_image_build_pipeline >>\"
            if [[ -n "<< pipeline.git.tag >>" || "<<pipeline.git.branch>>" == "main" ]] && [[ "<< pipeline.parameters.skip_image_build_pipeline >>" == "false" ]]
            then
              echo "Building images"
            else
              echo "Skipping image build"
            fi
      - when:
          condition:
            and:
              - or:
                  - << pipeline.git.tag >>
                  - equal: [ main, << pipeline.git.branch >> ]
              - not: << pipeline.parameters.skip_image_build_pipeline >>
          steps:
            - continuation/continue:
                parameters: '{}'
                configuration_path: /tmp/workspace/build.yml
      - run:
          name: Show pipeline triggers
          command: |
            echo Condition variables for running pipeline:
            echo pipeline.parameters.run_pipeline \"<< pipeline.parameters.run_pipeline >>\"
            if [[ "<< pipeline.parameters.run_pipeline >>" == "true" ]]
            then
              echo "Running pipeline"
            else
              echo "Skipping pipeline"
            fi
      - when:
          condition: << pipeline.parameters.run_pipeline >>
          steps:
            - continuation/continue:
                parameters: '{}'
                configuration_path: /tmp/workspace/pipeline.yml
workflows:
  setup:
    jobs:
      - generate_config
      - run_config:
          requires:
            - generate_config
