version: 2.1
setup: true
orbs:
  docker: circleci/docker@2.1.1
  python: circleci/python@2.0.3
  continuation: circleci/continuation@0.1.0
executor:
  base:
    docker:
      - image: cimg/base
        tag: stable
jobs:
  generate_config:
    executor:
      name: python/default
      tag: '3.10'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ci/
      - run:
          name: Generate Pipeline Assets
          command: |
            mkdir -p /tmp/generated
            python3 ci/circleci.py /tmp/generated test_es_url
      - persist_to_workspace:
          root: /tmp/generated/
          paths:
            - pipeline.yml
      - store_artifacts:
          path: /tmp/generated
  run_config:
    executor: continuation/default
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - continuation/continue:
          parameters: '{}'
          configuration_path: /tmp/workspace/pipeline.yml
workflows:
  setup:
    jobs:
      - generate_config
      - run_config:
          requires:
            - generate_config
