apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  labels:
    app: pushgateway
spec:
  ports:
    - port: 9091
      protocol: TCP
      targetPort: http-pg
      name: http-pg
  selector:
    app: pushgateway
  sessionAffinity: None
