apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod2pod
  labels:
    app: pod2pod
spec:
  replicas: 2
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              type: dummy