apiVersion: v1
baseDomain: isovalent.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: rook-ocp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: Cilium
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-west-2
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMWE5ZmRlZjY2ZDM4NDU1YjgwYmE1OTU1YzNmMzM3YTI6SVdBWEFDTlYxNEFQSjVFUFhMVFJPWTBHOUZTSkpaRVI5NVlBTVpPTFFVWE02Mlc2RkNCNk00UEU1VTA5U0RPMg==","email":"rook@isovalent.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfMWE5ZmRlZjY2ZDM4NDU1YjgwYmE1OTU1YzNmMzM3YTI6SVdBWEFDTlYxNEFQSjVFUFhMVFJPWTBHOUZTSkpaRVI5NVlBTVpPTFFVWE02Mlc2RkNCNk00UEU1VTA5U0RPMg==","email":"rook@isovalent.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLTRmYjk3MTZhLWY3MTEtNDU1Ny04YmIwLWQzMWIzNzBhZGMzZTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXpZamcxWkRnNU9HTmlZelEwWmpjME9UVXdNemhtWVRnME5qaGpORGN6TlNKOS5qRDZlTVNWTzhMa1FsMFhJSU9MbE94YklTNG9qYXhMaWcxOVRBa1FsWFBPRURlMWNxcHRHbFBlOG9SYW1HaTJZV0cxWDExbkpHYjZuYlc1eHMyaS1aVjNobFl2c1hMYXhjaXBrTV8yZFBnSEJTeW42N2Z5TkR4Q0VRbkh6QVMyN1dlaXZRUlZJWkVWdVN5cnFkMzRMQXNDci1fa3VMaUhYOGoydndXR2JDbzVON2x2TmgtOHdFRHhfRjlobWZJMVRsT1JOUG1tbzcxbWJOUHNhZ1J1V05ad3p4TmJ0SjFlQ0EwRGxaNWhwdHlGb21fdy04cHdlbXZjNjdJWVNSUWJ0ZHZtVTJlMkVPbDZZMEpBb3pCMTMtLUNROEN0dlVIN3Vmc0lKY1NXXzdOUHRkcUtHVHlabkZmVkFmZzg1SVNqdFYtcm13MHkxQWJiVUZERnpqQ01CQ3ZMTzlMUTk2cEczZVcwMWVYal9YVW1KcVZMWVRCeFBiU1kteVBmWmFFR2pCOFRCb19LQUxReEdHM1pYRnQxYTNzU1p1UWpCYkxDa0pTQS10QURad0p3eFJnMUFtdVVTdjRJc1M1V0JYTFN1MUp3YUtheFhaNjBpVHZKWWI4dXg3RXFnbWdkd0dDdm0ySWxmcHJaT1Y2U0VZNUtMZDFSc3FXRmtDR0Q5V1g5Q25UYmZuNlhTWW5obF9FQUdFa2dlN1J0UnpHckg2Q2laMzRzNkVDdlFsQXZMci14WXB2RUxLZlNlRkQ1OVItcm91Ny1CdWFIdFptM3NzVUpidG5HVmZJSko0c09HMjRXMTNnSG5KUjZFMGZGaDFfeThLc3ZQZl93SlNCUy1HRzBfTW96Yy1WX2FYOW9saU40OVc5T0wyYnNBSEhBNDEzRUU1cXFqd0FLVnRtbw==","email":"rook@isovalent.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLTRmYjk3MTZhLWY3MTEtNDU1Ny04YmIwLWQzMWIzNzBhZGMzZTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXpZamcxWkRnNU9HTmlZelEwWmpjME9UVXdNemhtWVRnME5qaGpORGN6TlNKOS5qRDZlTVNWTzhMa1FsMFhJSU9MbE94YklTNG9qYXhMaWcxOVRBa1FsWFBPRURlMWNxcHRHbFBlOG9SYW1HaTJZV0cxWDExbkpHYjZuYlc1eHMyaS1aVjNobFl2c1hMYXhjaXBrTV8yZFBnSEJTeW42N2Z5TkR4Q0VRbkh6QVMyN1dlaXZRUlZJWkVWdVN5cnFkMzRMQXNDci1fa3VMaUhYOGoydndXR2JDbzVON2x2TmgtOHdFRHhfRjlobWZJMVRsT1JOUG1tbzcxbWJOUHNhZ1J1V05ad3p4TmJ0SjFlQ0EwRGxaNWhwdHlGb21fdy04cHdlbXZjNjdJWVNSUWJ0ZHZtVTJlMkVPbDZZMEpBb3pCMTMtLUNROEN0dlVIN3Vmc0lKY1NXXzdOUHRkcUtHVHlabkZmVkFmZzg1SVNqdFYtcm13MHkxQWJiVUZERnpqQ01CQ3ZMTzlMUTk2cEczZVcwMWVYal9YVW1KcVZMWVRCeFBiU1kteVBmWmFFR2pCOFRCb19LQUxReEdHM1pYRnQxYTNzU1p1UWpCYkxDa0pTQS10QURad0p3eFJnMUFtdVVTdjRJc1M1V0JYTFN1MUp3YUtheFhaNjBpVHZKWWI4dXg3RXFnbWdkd0dDdm0ySWxmcHJaT1Y2U0VZNUtMZDFSc3FXRmtDR0Q5V1g5Q25UYmZuNlhTWW5obF9FQUdFa2dlN1J0UnpHckg2Q2laMzRzNkVDdlFsQXZMci14WXB2RUxLZlNlRkQ1OVItcm91Ny1CdWFIdFptM3NzVUpidG5HVmZJSko0c09HMjRXMTNnSG5KUjZFMGZGaDFfeThLc3ZQZl93SlNCUy1HRzBfTW96Yy1WX2FYOW9saU40OVc5T0wyYnNBSEhBNDEzRUU1cXFqd0FLVnRtbw==","email":"rook@isovalent.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+V7d7W4oYdca3I+IAhjgGFgTlut7QTith1vxPwnOwU8CvZ1SCqRd123XYWGr5gT4+bQzHbx5RJqySLXNJs4coRiEHgCDfjF6GmoRrrvrC4yPg9+lLo0YF6L3PB2k8LWz+YofsiRhs1ptYD7oUetqhTmk4DrODY6a93S66PEN7cugg4eEABcW/XFiYVPJswzqiRum9yxuxKG6xkyxy7LpQl/wm5q9Swg3tfZ+to55C3cnZgxaizedWgkPCjdO0jzLtCMJD8xLxd4iFVbDq+/mpctqA9YZTn5d/BT9DPKBpxcUZxTZSArCJV7moHHJEAYPiJlG5n+cQYhckkiyu732XGtLIcdgjK7uuUk1sobgGkyNZ3Uw3OqxBvIHoV7C147pJODuQT9qh2386H1DTaDX9FF9EKrdwPqooE+PjMV2Y08UxbTKIM9DEI+s4D2yGBtVgB4+Wt5XNWzz7HfjgO/12s7BFy5i1upxgfLNgFzEgth4dE4W5bwvNSXmDa48Q2vU= jtaleric@rook-mobile
