apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- grafana.yaml
- service.yaml
- datasources.yaml
- dashboards.yaml
- dashboard-provider.yaml
patches:
- path: dashboards/node-exporter-dashboard.yaml
