---

- name: Capture nodes
  shell: |
   kubectl get nodes --no-headers -o custom-columns=:.metadata.name
  register: node_list

- name: Create CM
  shell: |
    export KUBECONFIG={{kubeconfig}};
    kubectl apply -f {{ role_path }}/files/cm-kernel.yaml

- name: Create DS
  shell: |
    export KUBECONFIG={{kubeconfig}};export KERNEL_VERSION={{kernel}};
    envsubst < {{ role_path }}/files/ds-kernel.yaml | kubectl apply -f -

- name: Check on the rollout
  shell: |
    export KUBECONFIG={{kubeconfig}};kubectl rollout status ds/node-initializer

- name: Restart GKE nodes
  shell: |
    yes | gcloud config set project {{ gke['project'] }}
    gcloud compute instances reset --zone {{ gke['region'] }} {{ item }}
  loop: "{{ node_list.stdout_lines }}"

- name: Delete DS
  shell: |
    export KUBECONFIG={{kubeconfig}};kubectl delete ds/node-initializer

- name: Check node status
  shell: |
    export KUBECONFIG={{kubeconfig}};kubectl wait --for=condition=Ready nodes --all --timeout=600s