{{- with lookup "v1" "Secret" .Release.Namespace "cilium-ca" }}

{{- $cacrt := index .data "ca.crt" }}
{{- $cakey := index .data "ca.key" }}
{{- $ca := buildCustomCert $cacrt $cakey -}}

{{- $cn := include "cmapisrv-mock.fullname" $ }}
{{- $ip := list "127.0.0.1" "::1" }}
{{- $dns := list (printf "%s.%s.svc" (include "cmapisrv-mock.fullname" $) $.Release.Namespace) }}
{{- $cert := genSignedCert $cn $ip $dns 365 $ca -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cmapisrv-mock.fullname" $ }}-server
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cmapisrv-mock.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key  | b64enc }}

{{- else }}
  {{- fail "Unable to retrieve Cilium CA certificate" }}
{{- end }}
