apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmapisrv-mock.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmapisrv-mock.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - name: etcd-metrics
      port: 9998
      protocol: TCP
      targetPort: etcd-metrics
    - name: mocker-metrics
      port: 9999
      protocol: TCP
      targetPort: mocker-metrics
  selector:
    {{- include "cmapisrv-mock.selectorLabels" . | nindent 4 }}
