apiVersion: v1
kind: Service
metadata:
  name: {{ include "cmapisrv-mock.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cmapisrv-mock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: etcd
      protocol: TCP
      name: etcd
  selector:
    {{- include "cmapisrv-mock.selectorLabels" . | nindent 4 }}
