name: Lint Go files

on:
  pull_request: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - workdir: cmapisrv-mock
          - workdir: egw-scale-utils

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          # renovate: datasource=golang-version depName=go
          go-version: 1.26.5
          cache-dependency-path: ${{ matrix.workdir }}/go.sum

      - name: Check module vendoring
        working-directory: ${{ matrix.workdir }}
        run: |
          go mod tidy
          go mod vendor
          test -z "$(git status --porcelain)" || (echo "please run 'go mod tidy && go mod vendor', and submit your changes"; exit 1)

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          # renovate: datasource=docker depName=golangci/golangci-lint
          version: v2.12.2
          skip-cache: true
          working-directory: ${{ matrix.workdir }}
          args: "--verbose --modules-download-mode=vendor"
